<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="5" passed="2" failed="3" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2022-02-02T07:15:14Z" name="Suite" finished-at="2022-02-02T07:15:22Z" duration-ms="7850">
    <groups>
    </groups>
    <test started-at="2022-02-02T07:15:14Z" name="AddPayeeValidTest" finished-at="2022-02-02T07:15:22Z" duration-ms="7850">
      <class name="BankingTestCases1.AddPayeeDatadriven">
        <test-method is-config="true" signature="init()[pri:0, instance:BankingTestCases1.AddPayeeDatadriven@32502377]" started-at="2022-02-02T02:15:09Z" name="init" finished-at="2022-02-02T02:15:14Z" duration-ms="4683" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- init -->
        <test-method signature="login()[pri:1, instance:BankingTestCases1.AddPayeeDatadriven@32502377]" started-at="2022-02-02T02:15:14Z" name="login" finished-at="2022-02-02T02:15:16Z" duration-ms="2194" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login -->
        <test-method signature="addPayee(java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:2, instance:BankingTestCases1.AddPayeeDatadriven@32502377]" started-at="2022-02-02T02:15:17Z" name="addPayee" data-provider="PayeeData" finished-at="2022-02-02T02:15:18Z" duration-ms="1225" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[Payee1]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[brampton20 ]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[abbbb]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[hydro]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- addPayee -->
        <test-method signature="addPayee(java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:2, instance:BankingTestCases1.AddPayeeDatadriven@32502377]" started-at="2022-02-02T02:15:18Z" name="addPayee" data-provider="PayeeData" finished-at="2022-02-02T02:15:19Z" duration-ms="863" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[Payee2]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[ brampton]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[abbbb]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[hydro]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [The new payee Payee1 was successfully created.] but found [The new payee Payee2 was successfully created.]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [The new payee Payee1 was successfully created.] but found [The new payee Payee2 was successfully created.]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertEqualsImpl(Assert.java:134)
	at org.testng.Assert.assertEquals(Assert.java:115)
	at org.testng.Assert.assertEquals(Assert.java:189)
	at org.testng.Assert.assertEquals(Assert.java:199)
	at BankingTestCases1.AddPayeeDatadriven.addPayee(AddPayeeDatadriven.java:83)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- addPayee -->
        <test-method signature="addPayee(java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:2, instance:BankingTestCases1.AddPayeeDatadriven@32502377]" started-at="2022-02-02T02:15:19Z" name="addPayee" data-provider="PayeeData" finished-at="2022-02-02T02:15:20Z" duration-ms="954" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[Payee3]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[brampton20 ]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[abbbb]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[hydro]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [The new payee Payee1 was successfully created.] but found [The new payee Payee3 was successfully created.]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [The new payee Payee1 was successfully created.] but found [The new payee Payee3 was successfully created.]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertEqualsImpl(Assert.java:134)
	at org.testng.Assert.assertEquals(Assert.java:115)
	at org.testng.Assert.assertEquals(Assert.java:189)
	at org.testng.Assert.assertEquals(Assert.java:199)
	at BankingTestCases1.AddPayeeDatadriven.addPayee(AddPayeeDatadriven.java:83)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- addPayee -->
        <test-method signature="addPayee(java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:2, instance:BankingTestCases1.AddPayeeDatadriven@32502377]" started-at="2022-02-02T02:15:21Z" name="addPayee" data-provider="PayeeData" finished-at="2022-02-02T02:15:21Z" duration-ms="924" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[Payee4]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[brampton20 ]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[abbbb]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[hydro]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [The new payee Payee1 was successfully created.] but found [The new payee Payee4 was successfully created.]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [The new payee Payee1 was successfully created.] but found [The new payee Payee4 was successfully created.]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertEqualsImpl(Assert.java:134)
	at org.testng.Assert.assertEquals(Assert.java:115)
	at org.testng.Assert.assertEquals(Assert.java:189)
	at org.testng.Assert.assertEquals(Assert.java:199)
	at BankingTestCases1.AddPayeeDatadriven.addPayee(AddPayeeDatadriven.java:83)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- addPayee -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:BankingTestCases1.AddPayeeDatadriven@32502377]" started-at="2022-02-02T02:15:22Z" name="tearDown" finished-at="2022-02-02T02:15:22Z" duration-ms="101" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- BankingTestCases1.AddPayeeDatadriven -->
    </test> <!-- AddPayeeValidTest -->
  </suite> <!-- Suite -->
</testng-results>
